### ISSUE TITLE
View as ANSI 觸發熱鍵

### ISSUE THREAD

**Issue by bingthian** [eight04/ansi-viewer#3]
可以為藏在右鍵選單中的 View as ANSI 設定觸發熱鍵嗎?
按第一次切換，按第二次切換回來

**Comment by eight04** [comment]
用途是？會常常在 ANSI 和源碼之間相互切換嗎？為什麼？

**Comment by bingthian** [comment]
相對於滑鼠選單，更喜歡熱鍵操作
而當以資料夾形式搭配 [上一頁] 瀏覽存檔時
有些檔案是尚未命名副檔名的，或是於文字檔中包含部份 ANSI 色碼，會想臨時檢視

**Comment by eight04** [comment]
對於這種狀況改副檔名比較有用？

不過能加上熱鍵也不是壞事。

**Comment by eight04** [comment]
Fixed in 2.0.0. 預設的熱鍵是 Alt+A。
