### ISSUE TITLE
合法副檔名清單

### ISSUE THREAD

**Issue by bingthian** [eight04/ansi-viewer#4]
建議讓使用者新增合法副檔名清單，不要只預設支援 .ans

**Comment by eight04** [comment]
用途是？目前我使用的 ANSI 編輯工具存檔時的預設檔名就是 [.ans](http://fileinfo.com/extension/ans)

**Comment by bingthian** [comment]
我習慣將 ANSI 圖形存為 .ans，將 ANSI 色彩文章存為 .bbs

**Comment by eight04** [comment]
看起來 .bbs 也是常用的副本名之一
http://fileinfo.com/extension/bbs

**Comment by bingthian** [comment]
我不知道 .bbs 的使用普及度如何
但對我的需求來說，至少將 .bbs 納入支援已足矣
另外，有時候也會遇到副檔名為 .ansi 的狀況，如果能一併支援就太好了

**Comment by eight04** [comment]
Fixed in 2.0.0.
