### ISSUE TITLE
將 HTTP 超連結字串轉換為可點擊的超連結

### ISSUE THREAD

**Issue by bingthian** [eight04/ansi-viewer#5]
將 HTTP 超連結字串轉換為可點擊的超連結
和一般網頁瀏覽中的超連結一樣

**Comment by eight04** [comment]
已經有很多類似 linkification 的 addon，例如 [Greasemonkey](https://addons.mozilla.org/zh-TW/firefox/addon/greasemonkey/) + [Linkify Plus Plus](https://greasyfork.org/en/scripts/4255-linkify-plus-plus)（Greasemonkey 預設是不在 file:// 上執行的，要調整一些[設定](http://stackoverflow.com/questions/9931115/run-greasemonkey-on-html-files-located-on-the-local-filesystem)）。

**Comment by bingthian** [comment]
我明白有此類 addon
但就像使用 BBSFox 如果還需要另搭套件，會有點不方便
如果不是在自己的電腦，就更不方便

**Comment by eight04** [comment]
使用 BBSFox 或 ANSI Viewer 並不需要另搭套件。
但如果你想要文字轉超連結的功能，就需要文字轉超連結的套件。

另外如果要在不同電腦上用相同套件，可以用 portable 版本或 Firefox sync。

**Comment by bingthian** [comment]
是想表達 BBSFox 有內建 文字轉超連結，他並沒有要求使用者另加此套件，讓套件的完整體驗較佳

無論如何，感謝你的建議
