### ISSUE TITLE
save as HTML

### ISSUE THREAD

**Issue by bingthian** [eight04/ansi-viewer#6]
可以在右鍵選單中添加 "save as HTML" 嗎?

**Comment by eight04** [comment]
Ctrl-S 存下來的即是 HTML 檔

**Comment by bingthian** [comment]
有試過 Ctrl-S 順利獲得 HTML 檔
不過希望能更醒目，這樣介紹別人使用會更加直覺
您自用兼分享雖已難能可貴，可是再加一點點調整，可以讓程式親和力更好

還有，目前版本如果不是直接瀏覽副檔名為 .ans 的檔案
而是透過 View as ANSI 來瀏覽，Ctrl-S 好像無法存為 HTML 檔

**Comment by eight04** [comment]
透過 View as ANSI 轉換時，由於開啟的是純文字檔，儲存的時候是以純文字檔的形式儲存的。

**Comment by eight04** [comment]
正在把 addon 用 webextension 重寫，很多實作都改了。
https://github.com/eight04/ansi-viewer/tree/dev-web-ext

以目前的狀況來說，轉換方法全部變成類似 右鍵 -> View as ANSI 的形式。也就是說即使直接開啟 .ans 檔再按 Ctrl-S，所儲存的還是純文字檔。後來找了兩個套件︰

* https://addons.mozilla.org/en-us/firefox/addon/save-page-we/
* https://addons.mozilla.org/zh-tw/firefox/addon/unmht/

Save Page WE 可以將頁面存成單獨 html 檔，但有些頁面無法作用。
UnMHT 可以將頁面存成單獨 mht 檔，但不相容 e10s。

可以再描述一下是在什麼狀況下會用到「轉成 HTML」的功能嗎？只需要 HTML？還是 CSS 和 JS 都要？

**Comment by bingthian** [comment]
將包含 ANSI 色彩的 BBS 文章轉成 HTML 發送給朋友
以及上傳至網頁空間，作為瀏覽器超連結指向的頁面

感謝您的用心! 
(沒想到為了完善一個功能，甚至需要換方式重寫... 也許不該輕易提issue|||)
(其實如果預設支援了 .bbs 副檔名，那按照原來的方式 Ctrl+S/另存新檔 亦無不可)

**Comment by eight04** [comment]
重寫是為了試試 web extension 的效果怎麼樣，對這個功能反而沒有幫助。

若是要將 .ans 檔轉成 .html，我傾向於另外寫一個 CLI 工具來做這件事，如此一來不需要依賴 Firefox，還可以進行批次轉換。

至於為何 Ctrl-S 會存成 HTML︰目前的轉換做法是在 Firefox 讀取檔案**前**直接把 ANSI 轉換成網頁，所以將 .ans 檔拉進 Firefox 內時，Firefox 會把 .ans 檔當作 HTML，Ctrl-S 才會儲存成 HTML。

但是 View as ANSI 選項，是在 Firefox 讀取檔案**之後**才把 ANSI 轉換成網頁，所以 Ctrl-S 時 Firefox 還是把它當作原本的文字檔。

有一個辦法是將 HTML 另外開一個視窗，如此一來在該視窗 Ctrl-S 就會辨認成網頁了。但這樣的步驟太繁瑣（開啟 .ans 檔 -> 把 HTML 開到新視窗 -> Ctrl-S 存檔），我認為另外做一個 CLI 工具是比較好的選擇。

若是真的想把目前看到的頁面內容給存下來，可以用前述的兩個套件或 https://addons.mozilla.org/zh-tw/firefox/addon/mozilla-archive-format/ 。

**Comment by eight04** [comment]
https://github.com/eight04/bbs-reader-cli
