### ISSUE TITLE
Firefox 54 hangs when loading .ans file

### ISSUE THREAD

**Issue by Keith94** [eight04/ansi-viewer#7]
For example: http://textfiles.com/holiday/santa.ans

> NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindowUtils.isParentWindowMainWidgetVisible]  nsPrompter.js:349

> Error: Script terminated by timeout at:
> bbsReader@moz-extension://48c528a1-d458-4b7c-b476-30667658810f/background/lib.js:238:12
> ANSI@moz-extension://48c528a1-d458-4b7c-b476-30667658810f/background/background.js:25:18
> convertAnsi@moz-extension://48c528a1-d458-4b7c-b476-30667658810f/background/background.js:72:14
> @moz-extension://48c528a1-d458-4b7c-b476-30667658810f/background/background.js:83:4
>   lib.js:238:12

**Comment by eight04** [comment]
Fixed in 2.0.2.
